### PR TITLE
adding other clients as possible solution

### PR DESCRIPTION
**Pull request by Stemby**
I think Rein should be client-agnostic.

### CODE REVIEW

**Comment by bitspill** [comment]
I'm open to the idea but perhaps word it as `Bitcoin Core (or alternative)`, `Bitcoin Core (or similar)` or `Bitcoin Core (or compatible)` otherwise where do you draw the line? 

`Bitcoin Core or Classic or Unlimited or XT or etc`

**Comment by weex** [comment]
People can use whatever they want to generate a Bitcoin address but I don't think it's wise for Rein to endorse anything that risks a contentious (<95%) hard fork.

**Comment by achow101** [comment]
I think it should just be generic like what @bitspill suggested, `Bitcoin Core (or similar)`

**Comment by Stemby** [comment]
Ok, I will fix my pull request.

**Comment by weex** [comment]
I don't know if it's possible, but can you update this so it only puts "(or similar)" in each of those references with no extra commits in between? There may be many clients that could generate an address but there's no need to mention any of them by name. There's a tool I prefer (https://github.com/weex/addrgen) that isn't core but I didn't point people to that since I really only trust Core to be generating secure addresses. If it's not possible then, please create a new pull request like that.

**Pull request merged**
